# Generated by Django 4.2.1 on 2023-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_PPM', '0003_post_category_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='other', max_length=255),
        ),
    ]
